/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'grimur' at '10/30/14 3:18 PM' with Gradle 2.1
 *
 * @author grimur, @date 10/30/14 3:18 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
